#Zbudujmy własny zestaw definicji środowiska dla aplikacji to-do. Zamierzamy połączyć środowisko programistyczne i środowisko testowe i upewnić się, że oba mogą działać na tej samej maszynie. Środowisko programistyczne powinno być domyślne, które można uruchomić za pomocą docker-compose up. Konfiguracja powinna:
#
#  Użyć lokalnego pliku bazy danych
#  Opublikować aplikacje na porcie 8089
#  Uruchomić wersję v2 aplikacji to-do


version: '3.7'
services:
  todo-db:
    image: ${TODO_DB_IMAGE}
    restart: always
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

  todo-web:
    image: ${TODO_WEB_IMAGE}
    restart: always
    ports:
      - "${TODO_WEB_PORT}:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    secrets:
      -  source: todo-db-password
      -  target: /app/config/secrets.json
volumes:
  todo-db:
    driver: local
secrets:
  ToDoDb:
    file: /app/config/secrets.json
