version: '3.7'
services:
  todo-db:
    image: ${TODO_DB_IMAGE}
    restart: always
    volumes:
      - ${PGDATA}:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres

  todo-web:
    image: ${TODO_WEB_IMAGE}
    restart: always
    ports:
      - "${TODO_WEB_PORT}:80"
    environment:
      - Database:Provider=Postgres
    depends_on:
      - todo-db
    secrets:
      -  source: todo-db-password
      -  target: /app/config/secrets.json
volumes:
  todo-db:
    driver: local
secrets:
  ToDoDb:
    file: /app/config/secrets.json
